### ISSUE TITLE
Louis Hedges (26819842) - code review for assignment 1

### ISSUE THREAD

**Issue by LMHedges** [ES-UoL/Assignment_1#4]
LGTM runs well and as intended. The program uses all the functions asked in the brief as well as the added class of Testing.cs.

Some use of exception handling was used for lines 48 to 64 in Testing.cs for then the user enters an invalid integer, however if the user enters a string or char the code breaks. A use of a menu system would be help as this allows the user to decide what they would like to do to the deck and the outcome wouldn't be pre-set.

**Comment by ES-UoL** [comment]
Thank you for the code review, I will look into implementing the changes that you have suggested.
